development:
  clients:
    default:
      database: crdmrkt_development
      hosts:
        - mongodb:27017
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: crdmrkt_test
      hosts:
        - mongodb:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5
