[build]
# Use our custom Dockerfile for Railway
dockerfilePath = "Dockerfile.railway"
# Force fresh builds to avoid gem cache issues
buildCommand = "echo 'Building with fresh gems...'"

[deploy]
# Start command for the Rails application
startCommand = "bundle exec rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[environments.production]
# Production-specific settings
variables = { RAILS_ENV = "production" }
